[tox]
requires =
    tox>=4
env_list =
    py{310,311,312,313,314}-django52
    py{312,313,314}-django60

[testenv]
deps =
    pytest
    pytest-django
    django52: django~=5.2.0
    django60: django~=6.0.0
set_env =
    DJANGO_SETTINGS_MODULE = tests.settings
    PYTHONPATH = {toxinidir}
commands =
    pytest
